import { useState, useMemo } from "react";
import styled from "styled-components";
import {
  Edit,
  Delete,
  Teams,
  Reports,
  User,
} from "../../../../components/common/Icons";
import { DataTable } from "../../../../shared/DataTable";
import { SortHeader } from "../../../../shared/SortHeader";
import { useReportStore } from "../../../../store/crm/reportStore";
import { fontSize, fontWeight } from "../../../../styles/mixins";

export const AppNameColumnHeading = styled.p`
  ${fontSize("12px")}
  ${fontWeight("500")}
  text-decoration: underline;
  color: ${({ theme }) => theme.colors.blue30};
`;

export const AppIndustriesInfo = styled.div`
  display: flex;
  flex-direction: column;

  .app_type_col {
    padding: 2px 4px;
    border-radius: 3px;
    border: 1px solid ${({ theme }) => theme.colors.blue30};
    color: ${({ theme }) => theme.colors.blue30};
  }
`;

export const AppSPanIconCover = styled.div`
  width: auto;
  height: 18px;
  display: flex;
  align-items: center;
  gap: 8px;

  & > svg {
    width: 16px;
    height: 16px;
  }

  & > p {
    ${fontSize("12px")}
    ${fontWeight("500")}
  }

  &.System {
    & > svg path {
      stroke: ${({ theme }) => theme.colors.magenta40};
    }
  }
  &.Admin {
    & > svg path {
      stroke: ${({ theme }) => theme.colors.green40};
    }
  }
  &.Sales {
    & > svg path {
      stroke: ${({ theme }) => theme.colors.yellow30};
    }
  }
`;

export const ListReports = () => {
  const { reports } = useReportStore();
  const [sorting, setSorting] = useState([]);
  const handleEdit = (id) => console.log(id);

  const columns = useMemo(
    () => [
      {
        id: "select",
        header: ({ table }) => (
          <input
            type="checkbox"
            id="select-row"
            checked={table.getIsAllPageRowsSelected()}
            onChange={table.getToggleAllPageRowsSelectedHandler()}
          />
        ),
        cell: ({ row }) => (
          <input
            type="checkbox"
            checked={row.getIsSelected()}
            onChange={row.getToggleSelectedHandler()}
          />
        ),
        enableSorting: false,
        enableHiding: false,
      },
      {
        accessorKey: "title",
        header: ({ column }) => (
          <SortHeader column={column} title="Report Title" />
        ),
        cell: ({ row }) => {
          const cname = row.original.title;
          return <AppNameColumnHeading>{cname}</AppNameColumnHeading>;
        },
      },
      {
        accessorKey: "reportType",
        header: <span>Report Type</span>,
      },
      {
        accessorKey: "timePeriod",
        header: () => <span>Time Period</span>,
      },
      {
        accessorKey: "generatedBy",
        header: ({ column }) => (
          <SortHeader column={column} title="Generated by" />
        ),
        cell: ({ row }) => {
          const sourceRec = row.original.generatedBy;
          return (
            <AppSPanIconCover className={sourceRec}>
              {sourceRec === "System" ? (
                <Reports />
              ) : sourceRec === "Admin" ? (
                <User />
              ) : (
                <Teams />
              )}
              <p>{sourceRec}</p>
            </AppSPanIconCover>
          );
        },
      },
      {
        accessorKey: "generatedAt",
        header: () => <span>Generated at</span>,
      },
      {
        accessorKey: "actions",
        header: "Action",
        cell: ({ row }) => {
          return (
            <div className="app_table_row_btns">
              <button
                className="app_table_edit_btn"
                onClick={() => handleEdit(row.original.id ?? "")}
              >
                <Edit />
              </button>
              <button
                className="app_table_delete_btn"
                onClick={() => handleEdit(row.original.id ?? "")}
              >
                <Delete />
              </button>
            </div>
          );
        },
      },
    ],
    [],
  );

  return (
    <DataTable
      columns={columns}
      data={reports}
      sorting={sorting}
      setSorting={setSorting}
      search={"title"}
      pageSize={10}
    />
  );
};
