import {
  Edit,
  Delete,
  Teams,
  Reports,
  User,
} from "../../../../components/common/Icons";
import { SortHeader } from "../../../../shared/SortHeader";
import { AppNameColumnHeading, AppSpanIconCover } from "./styles";

export const createReportColumns = ({ onEdit, onDelete }) => [
  {
    id: "select",
    header: ({ table }) => (
      <input
        type="checkbox"
        id="select-row"
        checked={table.getIsAllPageRowsSelected()}
        onChange={table.getToggleAllPageRowsSelectedHandler()}
      />
    ),
    cell: ({ row }) => (
      <input
        type="checkbox"
        checked={row.getIsSelected()}
        onChange={row.getToggleSelectedHandler()}
      />
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "title",
    header: ({ column }) => <SortHeader column={column} title="Report Title" />,
    cell: ({ row }) => {
      return <AppNameColumnHeading>{row.original.title}</AppNameColumnHeading>;
    },
  },
  {
    accessorKey: "reportType",
    header: <span>Report Type</span>,
  },
  {
    accessorKey: "timePeriod",
    header: () => <span>Time Period</span>,
  },
  {
    accessorKey: "generatedBy",
    header: ({ column }) => <SortHeader column={column} title="Generated by" />,
    cell: ({ row }) => {
      const generatedBy = row.original.generatedBy;
      const iconMap = {
        System: <Reports />,
        Admin: <User />,
        Team: <Teams />,
      };
      const icon = iconMap[generatedBy] || <Teams />;
      return (
        <AppSpanIconCover className={generatedBy}>
          {icon}
          <p>{generatedBy}</p>
        </AppSpanIconCover>
      );
    },
  },
  {
    accessorKey: "generatedAt",
    header: () => <span>Generated at</span>,
  },
  {
    accessorKey: "actions",
    header: "Action",
    cell: ({ row }) => (
      <div className="app_table_row_btns">
        <button
          className="app_table_edit_btn"
          onClick={() => onEdit(row.original.id)}
        >
          <Edit />
        </button>
        <button
          className="app_table_delete_btn"
          onClick={() => onDelete(row.original.id)}
        >
          <Delete />
        </button>
      </div>
    ),
  },
];
