export const paths = {
  verifiEmail: "/",
  login: "/login",
  register: "/register",
  admin: "/:username",
  reports: "reports",
  vendors: "vendors",
  company: "companies",
  status: "status",
  warehouse: "warehouse",
  onboard: "resource-onboard",
  members: "members-list",
  salaries: "members-salary",
  attendances: "members-attendance",
};
