export const paths = {
  verifiEmail: "/",
  login: "/login",
  register: "/register",

  /** root */
  admin: "/:username",
  pms: "/:username/pms",
  erp: "/:username/erp",
  cms: "/:username/cms",
  hr: "/:username/hr",
  invt: "/:username/invt",

  /** CRM */
  leadinfo: "lead-information",
  leadassign: "lead-assignment",
  followup: "follow-up",
  pipeline: "sales-pipeline",
  pipelineQualified: "pipeline-qualified",
  pipelineProposal: "pipeline-proposal",
  pipelineWon: "pipeline-won",
  pipelineLost: "pipeline-lost",
  crmcustomers: "customers",
  crmbilling: "crm-billings",
  crmreport: "crm-reports",
  crmsettings: "crm-settings",

  /** hr */
  hrshifting: "shifting-details",
  hrholiday: "holiday-lists",
  hronboard: "on-boarding",
  hroffboard: "off-boarding",
  hremployee: "employee-lists",
  hrattendance: "attendance-info",
  hrleaves: "leaves-info",
  hrsalary: "salary-details",
  hrprovident: "provident-fund",
  hrtax: "taxes",
  hrinsurence: "insurence-info",
  hrtraining: "paid-training",
  hrnonpaidtraining: "non-paid-training",

  /** Next */
  reports: "reports",
  vendors: "vendors",
  company: "companies",
  status: "status",
  warehouse: "warehouse",
  products: "products",
  return: "returns",
  onboard: "resource-onboard",
  members: "members-list",
  salaries: "members-salary",
  attendances: "members-attendance",
};
